GET http://localhost:8080/item/ HTTP/1.1

###

POST http://localhost:8080/item/incluir HTTP/1.1
content-type: application/json

{
    "nome": "CocaCola",
    "tipoItem": 0,
    "valor": 6.5,
    "qtdRefeicao": 8,
    "tempoPreparo": 2.9

    //alterar os campos aqui
}



//------------CLIENTES----------------------
###


GET http://localhost:8080/cliente/ HTTP/1.1

###
POST http://localhost:8080/cliente/incluir HTTP/1.1
content-type: application/json

{
    "email": "monique@gmail.com",
    "senha": "monique",
    "nome": "Monique",
    "cpf": "22222222"
}


//---------------------------------------------


###
GET http://localhost:8080/bairro/ HTTP/1.1

###

POST http://localhost:8080/bairro/incluir/ HTTP/1.1
content-type: application/json

{
    "nome": "Barredo",
    "valorFrete": "1.50"

    //alterar os campos aqui
}

###
GET http://localhost:8080/endereco/ HTTP/1.1


###
POST  http://localhost:8080/endereco/incluir HTTP/1.1
content-type: application/json

{
    "logradouro": "Rua dos Jessuitas",
    "numero": "16",
    "complemento": "Condominio Mar do Norte",
    "cidade": "Macae",
    "cep": "384834"

    //alterar os campos aqui
}


//----------------FUNCIONARIOS-------------------
###

GET http://localhost:8080/funcionario/ HTTP/1.1

###
POST http://localhost:8080/funcionario/incluir HTTP/1.1
content-type: application/json

{
    "nome": "Paulo Antonio",
    "cargo": "Garçom",
    "login": "paulo",
    "senha": "paulo123",
    "gerente": "false",
    "cpf": "3333333",
    "email": "paulo@restauranteds1.com.br",
    "endereco": {
      "id": 1,
      "logradouro": "Rua 123",
      "numero": "98",
      "complemento": "Travessa 18",
      "bairro": {
        "id": 1,
        "nome": "Sao Jose Do Barreto",
        "valorFrete": 11.5
      },
      "cidade": "Macaé",
      "uf": "AC",
      "cep": "2525536"
    }

}
###
PUT http://localhost:8080/funcionario/alterar/68 HTTP/1.1
content-type: application/json

{
    "nome": "Andressa Soares",
    "cargo": "Gerente de Atendimento",
    "login": "andressa",
    "senha": "andressa123",
    "gerente": false,
    "cpf": "12315125125",
    "email": "andressa@ds1.com.br"

    
}

###
POST http://localhost:8080/funcionario/login HTTP/1.1
content-type: application/json

{
    "login": "PEDRO",
    "senha": "pedro123"
}


###

GET http://localhost:8080/item/carrinho/valortotal HTTP/1.1

###

GET http://localhost:8080/item/carrinho/remover/5 HTTP/1.1

###



//---------------------------ENDEREÇO--------------------------

###

GET http://localhost:8080/endereco/ HTTP/1.1

###
POST http://localhost:8080/endereco/incluir HTTP/1.1
content-type: application/json

{
    "logradouro": "Rua 123",
    "numero": "98",
    "complemento": "Travessa 18",
    "cidade": "Macaé",
    "uf": "AC",
    "cep": "2525536"
}